// Dagens Ord — Word of the Day (Norwegian)
// A curated list of uncommon/interesting Norwegian words with descriptions.
// One word per day, cycling based on day-of-year.

export interface DagensOrd {
  ord: string;
  ordklasse: string; // noun, verb, adjective, etc.
  beskrivelse: string;
}

const ordliste: DagensOrd[] = [
  { ord: "Eldhug", ordklasse: "substantiv", beskrivelse: "Glødende begeistring eller iver for noe." },
  { ord: "Blundstyre", ordklasse: "substantiv", beskrivelse: "Dårlig ledelse eller styre preget av inkompetanse." },
  { ord: "Døgnvill", ordklasse: "adjektiv", beskrivelse: "Å ha mistet oversikten over tid og døgnrytme." },
  { ord: "Fjellvett", ordklasse: "substantiv", beskrivelse: "Kunnskap og respekt for farer og regler i fjellet." },
  { ord: "Utepils", ordklasse: "substantiv", beskrivelse: "En øl som nytes utendørs, gjerne første gang om våren." },
  { ord: "Koselig", ordklasse: "adjektiv", beskrivelse: "En varm, hyggelig og intim stemning. Vanskelig å oversette direkte." },
  { ord: "Forfjamset", ordklasse: "adjektiv", beskrivelse: "Å være forvirra, overrumplet, og usikker på hva man skal gjøre." },
  { ord: "Dugnad", ordklasse: "substantiv", beskrivelse: "Frivillig, ulønnet arbeid som gjøres i fellesskap for et felles mål." },
  { ord: "Pålegg", ordklasse: "substantiv", beskrivelse: "Alt man kan legge på en brødskive – ost, syltetøy, kjøttpålegg osv." },
  { ord: "Peiskos", ordklasse: "substantiv", beskrivelse: "Den behagelige følelsen av å sitte foran en varm peis." },
  { ord: "Innfall", ordklasse: "substantiv", beskrivelse: "En plutselig, uventet idé eller lyst." },
  { ord: "Ildsjel", ordklasse: "substantiv", beskrivelse: "En person som brenner for en sak og legger ned stor innsats." },
  { ord: "Matpakke", ordklasse: "substantiv", beskrivelse: "Medbrakt lunsj, typisk brødskiver pakket inn i papir." },
  { ord: "Trollbundet", ordklasse: "adjektiv", beskrivelse: "Fullstendig fascinert, som om man er under et trolls magi." },
  { ord: "Skjønnlitteratur", ordklasse: "substantiv", beskrivelse: "Litteratur som er oppdiktet, som romaner, noveller og dikt." },
  { ord: "Kjærlighet", ordklasse: "substantiv", beskrivelse: "Dyp hengivenhet og varme følelser for en annen person." },
  { ord: "Etterpåklok", ordklasse: "adjektiv", beskrivelse: "Å innse hva man burde ha gjort etter at det er for sent." },
  { ord: "Vindskjev", ordklasse: "adjektiv", beskrivelse: "Skjevt, vridd eller bøyd av vind – brukes om bygg eller trær." },
  { ord: "Svalgang", ordklasse: "substantiv", beskrivelse: "En åpen, overdekket gang langs utsiden av en bygning." },
  { ord: "Skrinnlagt", ordklasse: "adjektiv", beskrivelse: "Lagt på is, skrinlagt. Satt til side uten å bli fullført." },
  { ord: "Drømmefanger", ordklasse: "substantiv", beskrivelse: "Person som jager drømmene sine, eller gjenstand som fanger drømmer." },
  { ord: "Høstvær", ordklasse: "substantiv", beskrivelse: "Det typiske været om høsten – regn, vind og fallende blader." },
  { ord: "Bjerke", ordklasse: "verb", beskrivelse: "Å flagre eller vimse rundt uten mål." },
  { ord: "Slarv", ordklasse: "substantiv", beskrivelse: "Sløvhet eller slurv i arbeid og oppførsel." },
  { ord: "Fomle", ordklasse: "verb", beskrivelse: "Å gjøre noe klumsete, lete etter noe med usikre hender." },
  { ord: "Gruble", ordklasse: "verb", beskrivelse: "Å tenke dypt og lenge over noe, ofte med bekymring." },
  { ord: "Solvarm", ordklasse: "adjektiv", beskrivelse: "Behagelig varm etter å ha vært i solen." },
  { ord: "Tøvær", ordklasse: "substantiv", beskrivelse: "Mildvær som får snø og is til å smelte." },
  { ord: "Skumring", ordklasse: "substantiv", beskrivelse: "Den svake belysningen mellom solnedgang og full mørke." },
  { ord: "Gufsen", ordklasse: "adjektiv", beskrivelse: "Kjølig, kald og gjennomtrengende – som et vindpust." },
  { ord: "Husvarme", ordklasse: "substantiv", beskrivelse: "Den gode varmen og atmosfæren i et hjem." },
  { ord: "Gladvær", ordklasse: "substantiv", beskrivelse: "Fint vær som setter folk i godt humør." },
  { ord: "Vedmod", ordklasse: "substantiv", beskrivelse: "En mild og vakker form for sorg eller melankoli." },
  { ord: "Tåkeprat", ordklasse: "substantiv", beskrivelse: "Uklart og forvirrende prat som ikke sier noe konkret." },
  { ord: "Ordhav", ordklasse: "substantiv", beskrivelse: "En overflod av ord; overdreven snakking." },
  { ord: "Svevende", ordklasse: "adjektiv", beskrivelse: "Uklart, ikke forankret i virkeligheten, vagt." },
  { ord: "Lettsindighet", ordklasse: "substantiv", beskrivelse: "Uforsiktig oppførsel uten å tenke på konsekvensene." },
  { ord: "Fjernsynt", ordklasse: "adjektiv", beskrivelse: "Å kunne se klart langt borte, men utydelig nært." },
  { ord: "Frampå", ordklasse: "adjektiv", beskrivelse: "Pågående, dristig, fremoverlent og direkte." },
  { ord: "Godslig", ordklasse: "adjektiv", beskrivelse: "Snill, vennlig og behagelig av natur." },
  { ord: "Knupp", ordklasse: "adjektiv", beskrivelse: "Liten, lubben og søt – gjerne om barn eller dyr." },
  { ord: "Brisen", ordklasse: "adjektiv", beskrivelse: "Lett beruset, i godt humør etter litt alkohol." },
  { ord: "Styvne", ordklasse: "verb", beskrivelse: "Å stivne, fryse til, eller bli ubevegelig." },
  { ord: "Nistirre", ordklasse: "verb", beskrivelse: "Å stirre intenst og gjennomborende på noen." },
  { ord: "Stusse", ordklasse: "verb", beskrivelse: "Å bli forundret, klø seg i hodet over noe merkelig." },
  { ord: "Krangle", ordklasse: "verb", beskrivelse: "Å ha en opphetet uenighet eller krangel med noen." },
  { ord: "Trauste", ordklasse: "verb", beskrivelse: "Å gå tungt og jevnt, uten å stoppe." },
  { ord: "Nøysom", ordklasse: "adjektiv", beskrivelse: "Fornøyd med lite, beskjeden i sine behov." },
  { ord: "Selvgod", ordklasse: "adjektiv", beskrivelse: "Overdrevent fornøyd med seg selv." },
  { ord: "Verdensfjern", ordklasse: "adjektiv", beskrivelse: "Avsondret fra virkeligheten, ikke i kontakt med omverdenen." },
  { ord: "Skadefro", ordklasse: "adjektiv", beskrivelse: "Å glede seg over andres uhell eller ulykke." },
  { ord: "Etterlengtet", ordklasse: "adjektiv", beskrivelse: "Noe man har ventet lenge på og ønsket sterkt." },
  { ord: "Gråvær", ordklasse: "substantiv", beskrivelse: "Overskyet vær uten sol – typisk norsk." },
  { ord: "Sjøsprøyt", ordklasse: "substantiv", beskrivelse: "Vanndråper som spruter opp fra bølger." },
  { ord: "Trillrund", ordklasse: "adjektiv", beskrivelse: "Helt rund, som en ball." },
  { ord: "Halvlys", ordklasse: "substantiv", beskrivelse: "Svakt lys, halvmørke – som i grålysningen." },
  { ord: "Stabbur", ordklasse: "substantiv", beskrivelse: "Gammelt norsk matlagerhus på stolper, beskyttet mot dyr." },
  { ord: "Nisselue", ordklasse: "substantiv", beskrivelse: "Rød, spiss topplue assosiert med julenissen." },
  { ord: "Krypinn", ordklasse: "substantiv", beskrivelse: "Et lite, koselig og enkelt tilfluktssted." },
  { ord: "Lefse", ordklasse: "substantiv", beskrivelse: "Tradisjonelt norsk flatbrød laget av potet eller mel." },
  { ord: "Kveldsbris", ordklasse: "substantiv", beskrivelse: "En lett, behagelig bris som kommer om kvelden." },
  { ord: "Turglad", ordklasse: "adjektiv", beskrivelse: "Glad i friluftsliv og turer i naturen." },
  { ord: "Solrenning", ordklasse: "substantiv", beskrivelse: "Det øyeblikket solen stiger over horisonten." },
  { ord: "Lettliva", ordklasse: "adjektiv", beskrivelse: "Bekymringsløs og munter av natur, lett til sinns." },
  { ord: "Trynetillegg", ordklasse: "substantiv", beskrivelse: "Et uoffisielt pristillegg man betaler bare fordi man er turist." },
  { ord: "Fjordarm", ordklasse: "substantiv", beskrivelse: "En smal del eller sidegrein av en fjord." },
  { ord: "Sommarfugl", ordklasse: "substantiv", beskrivelse: "Sommerfugl – et vakkert insekt med fargerike vinger." },
  { ord: "Skinntørr", ordklasse: "adjektiv", beskrivelse: "Helt tørr, uten en dråpe fuktighet." },
  { ord: "Stuvning", ordklasse: "substantiv", beskrivelse: "Hvit saus med grønnsaker – en norsk husmanskost-klassiker." },
  { ord: "Nattmørke", ordklasse: "substantiv", beskrivelse: "Det dype mørket som finnes midt på natten." },
  { ord: "Røyse", ordklasse: "substantiv", beskrivelse: "En haug med steiner, ofte brukt som markering i fjellet." },
  { ord: "Kjøttgryte", ordklasse: "substantiv", beskrivelse: "En varm og mettende gryte med kjøtt og grønnsaker." },
  { ord: "Duggfrisk", ordklasse: "adjektiv", beskrivelse: "Frisk og ny, som en morgen med dugg." },
  { ord: "Gjenklang", ordklasse: "substantiv", beskrivelse: "Ekko eller ettervirkninger av noe som har skjedd." },
  { ord: "Ovundsjuk", ordklasse: "adjektiv", beskrivelse: "Misunnelig, sjalu på andres suksess eller eiendeler." },
  { ord: "Ordsnill", ordklasse: "adjektiv", beskrivelse: "Dyktig med ord og formuleringer." },
  { ord: "Sommardag", ordklasse: "substantiv", beskrivelse: "En lang, varm dag om sommeren, gjerne med sol." },
  { ord: "Knallhard", ordklasse: "adjektiv", beskrivelse: "Ekstremt hard og uforsonlig." },
  { ord: "Bølgeskvulp", ordklasse: "substantiv", beskrivelse: "Den myke lyden av bølger som slår forsiktig." },
  { ord: "Geitost", ordklasse: "substantiv", beskrivelse: "Brun, søtlig norsk ost laget av geitmlk." },
  { ord: "Bortkomst", ordklasse: "substantiv", beskrivelse: "Å ha gått seg bort, å være i villrede." },
  { ord: "Vindstille", ordklasse: "adjektiv", beskrivelse: "Helt stille luft, uten et vindpust." },
  { ord: "Oppkomme", ordklasse: "substantiv", beskrivelse: "En kilde der vann bobler opp fra bakken." },
  { ord: "Skravle", ordklasse: "verb", beskrivelse: "Å prate i vei livlig, gjerne om uviktige ting." },
  { ord: "Motvind", ordklasse: "substantiv", beskrivelse: "Vind som blåser imot deg – også brukt om motgang i livet." },
  { ord: "Mæle", ordklasse: "substantiv", beskrivelse: "Evne til å snakke; «å miste mælet» betyr å bli stum av sjokk." },
  { ord: "Somle", ordklasse: "verb", beskrivelse: "Å bruke unødvendig lang tid, nøle eller tulle." },
  { ord: "Blåmandag", ordklasse: "substantiv", beskrivelse: "Mandagen etter en helg med for mye fest." },
  { ord: "Gnåle", ordklasse: "verb", beskrivelse: "Å mase, klage eller sutre gjentatte ganger." },
  { ord: "Kjæledegge", ordklasse: "verb", beskrivelse: "Å forkjæle noen overdrevent, gi dem alt de ønsker." },
  { ord: "Sørpe", ordklasse: "substantiv", beskrivelse: "Halvflytende snø og is blandet med vann." },
  { ord: "Midnattssol", ordklasse: "substantiv", beskrivelse: "Fenomenet der solen ikke går ned om sommeren i nord." },
  { ord: "Ruskevær", ordklasse: "substantiv", beskrivelse: "Stygt vær med vind og regn." },
  { ord: "Grøtlykke", ordklasse: "substantiv", beskrivelse: "Lykken ved å finne mandelen i grøten på julaften." },
  { ord: "Kramgod", ordklasse: "adjektiv", beskrivelse: "Så søt og fin at man vil klemme vedkommende." },
  { ord: "Skrøne", ordklasse: "substantiv", beskrivelse: "En overdrevet eller oppdiktet historie." },
  { ord: "Småprater", ordklasse: "substantiv", beskrivelse: "Lett og uforpliktende samtale." },
  { ord: "Morgenfugl", ordklasse: "substantiv", beskrivelse: "En person som fungerer best tidlig om morgenen." },
  { ord: "Nattugla", ordklasse: "substantiv", beskrivelse: "En person som holder seg oppe sent og trives om natten." },
  { ord: "Stavkirke", ordklasse: "substantiv", beskrivelse: "Middelalderkirke bygget av stående trestammer – unikt norsk." },
  { ord: "Orrfugl", ordklasse: "substantiv", beskrivelse: "En stor skogsfugl kjent for sitt dramatiske spillrituale." },
  { ord: "Snøfnugg", ordklasse: "substantiv", beskrivelse: "En enkelt, unik krystall av frosset vann som faller fra himmelen." },
  { ord: "Slåpekamp", ordklasse: "substantiv", beskrivelse: "En kamp som utspiller seg på slep, tungt og seigt." },
  { ord: "Oppstyr", ordklasse: "substantiv", beskrivelse: "Bråk, uro og oppmerksomhet rundt noe." },
  { ord: "Sinnsstemning", ordklasse: "substantiv", beskrivelse: "Den følelsesmessige tilstanden man befinner seg i." },
  { ord: "Godlynt", ordklasse: "adjektiv", beskrivelse: "Vennlig og snill av natur." },
  { ord: "Tannfelling", ordklasse: "substantiv", beskrivelse: "Når barn mister melketennene sine – en stor begivenhet." },
  { ord: "Fjelltind", ordklasse: "substantiv", beskrivelse: "Den spisse toppen av et fjell." },
  { ord: "Skogsbrann", ordklasse: "substantiv", beskrivelse: "En ukontrollert brann som sprer seg gjennom skogen." },
  { ord: "Julefred", ordklasse: "substantiv", beskrivelse: "Den rolige og fredelige stemningen rundt juletider." },
  { ord: "Spretten", ordklasse: "adjektiv", beskrivelse: "Sprek, livlig og med mye energi." },
  { ord: "Stotrende", ordklasse: "adjektiv", beskrivelse: "Nølende, hakkende tale som om man leter etter ord." },
  { ord: "Sjøsyk", ordklasse: "adjektiv", beskrivelse: "Kvalm av sjøens bevegelser; reisesyk til sjøs." },
  { ord: "Apekatten", ordklasse: "substantiv", beskrivelse: "Alfakrøllen (@) – det norske navnet på «krøllalfa»." },
  { ord: "Finlesing", ordklasse: "substantiv", beskrivelse: "Grundig og nøye gjennomlesning av en tekst." },
  { ord: "Bråstopp", ordklasse: "substantiv", beskrivelse: "En plutselig og uventet stopp i noe." },
  { ord: "Tunnelsyn", ordklasse: "substantiv", beskrivelse: "Å kun se én ting og overse alt rundt – metaforisk." },
  { ord: "Lydmur", ordklasse: "substantiv", beskrivelse: "Hastigheten der lyd bryter gjennom; metafor for en grense." },
  { ord: "Grøftekant", ordklasse: "substantiv", beskrivelse: "Kanten langs en grøft ved veien." },
  { ord: "Slagferdig", ordklasse: "adjektiv", beskrivelse: "Rask med kløktige svar og replikker." },
  { ord: "Smørhull", ordklasse: "substantiv", beskrivelse: "Et lunt, beskyttet sted med godt klima – f.eks. i en dal." },
  { ord: "Frysepunkt", ordklasse: "substantiv", beskrivelse: "Temperaturen der vann fryser til is: null grader." },
  { ord: "Klondyke", ordklasse: "substantiv", beskrivelse: "Et sted med kaotisk opportunisme og gullfeber-stemning." },
  { ord: "Bakevje", ordklasse: "substantiv", beskrivelse: "Et stille sted i strømmen der vannet renner bakover." },
  { ord: "Motbydelig", ordklasse: "adjektiv", beskrivelse: "Ekstremt ekkelt, frastøtende." },
  { ord: "Drøvtygger", ordklasse: "substantiv", beskrivelse: "Dyr som tygger maten to ganger – men også: en langsom tenker." },
  { ord: "Sorgmunter", ordklasse: "adjektiv", beskrivelse: "En blanding av sorg og munterhet – bittersøt." },
  { ord: "Ølhall", ordklasse: "substantiv", beskrivelse: "En stor hall der man kan nyte øl i hyggelig selskap." },
  { ord: "Fiskesuppe", ordklasse: "substantiv", beskrivelse: "Klassisk norsk suppe med fisk, melk og grønnsaker." },
  { ord: "Tullebukk", ordklasse: "substantiv", beskrivelse: "En som tøyser og tuller mye." },
  { ord: "Snurrepiperi", ordklasse: "substantiv", beskrivelse: "Noe som er underlig, pussig eller latterlig." },
  { ord: "Rabagast", ordklasse: "substantiv", beskrivelse: "En bråkete og vill person, gjerne et barn." },
  { ord: "Sklarkehjul", ordklasse: "substantiv", beskrivelse: "Å slå hjul – en gymnastisk øvelse sidelengs." },
  { ord: "Pjusk", ordklasse: "adjektiv", beskrivelse: "Å se sliten, syk eller stakkarslig ut." },
  { ord: "Søvnig", ordklasse: "adjektiv", beskrivelse: "Trøtt, døsig, klar for å sove." },
  { ord: "Dagdrøm", ordklasse: "substantiv", beskrivelse: "Å fantasere med åpne øyne midt på dagen." },
  { ord: "Nysådd", ordklasse: "adjektiv", beskrivelse: "Jord som akkurat har fått frø i seg." },
  { ord: "Laksefiske", ordklasse: "substantiv", beskrivelse: "Den norske tradisjonen med å fiske laks i elver." },
  { ord: "Stuevarm", ordklasse: "adjektiv", beskrivelse: "Behagelig varm som inne i en oppvarmet stue." },
  { ord: "Treghet", ordklasse: "substantiv", beskrivelse: "Mangel på fart og energi; motvilje mot endring." },
  { ord: "Snøblind", ordklasse: "adjektiv", beskrivelse: "Midlertidig blindet av sterkt sollys som reflekteres av snø." },
  { ord: "Kulde", ordklasse: "substantiv", beskrivelse: "Lav temperatur som man kjenner på kroppen." },
  { ord: "Fyrtårn", ordklasse: "substantiv", beskrivelse: "En høy bygning med lysignal for å veilede sjøfarende." },
  { ord: "Villspor", ordklasse: "substantiv", beskrivelse: "Feil retning i etterforskning eller tankegang." },
  { ord: "Hverdagslig", ordklasse: "adjektiv", beskrivelse: "Vanlig, alminnelig, uten noe spesielt." },
  { ord: "Husfred", ordklasse: "substantiv", beskrivelse: "Fred og ro i hjemmet." },
  { ord: "Gnagsår", ordklasse: "substantiv", beskrivelse: "Sår som oppstår av friksjon, f.eks. fra sko." },
  { ord: "Utflukt", ordklasse: "substantiv", beskrivelse: "En kort, hyggelig reise eller dagstur." },
  { ord: "Kvikk", ordklasse: "adjektiv", beskrivelse: "Rask, oppvakt og smart." },
  { ord: "Etterslep", ordklasse: "substantiv", beskrivelse: "Arbeid eller oppgaver som hoper seg opp og gjenstår." },
  { ord: "Kos", ordklasse: "substantiv", beskrivelse: "Hygge, varme og nærhet – en norsk livsstil." },
  { ord: "Skvaldrekål", ordklasse: "substantiv", beskrivelse: "Et ugress som er nesten umulig å bli kvitt." },
  { ord: "Snøbyge", ordklasse: "substantiv", beskrivelse: "Et plutselig og kortvarig snøfall." },
  { ord: "Bergtatt", ordklasse: "adjektiv", beskrivelse: "Betatt, fullstendig trollbundet – opprinnelig dratt inn i berget." },
  { ord: "Skavank", ordklasse: "substantiv", beskrivelse: "En liten feil eller mangel, oft om helseproblemer." },
  { ord: "Nøktern", ordklasse: "adjektiv", beskrivelse: "Edru, saklig og realistisk – uten overdrivelser." },
  { ord: "Topptur", ordklasse: "substantiv", beskrivelse: "Skitur opp til en fjelltopp og kjøring ned igjen." },
  { ord: "Blåfjell", ordklasse: "substantiv", beskrivelse: "Fjell som ser blålige ut i horisonten." },
  { ord: "Leirbål", ordklasse: "substantiv", beskrivelse: "Bål man tenner på leirplass ute i naturen." },
  { ord: "Fjellheim", ordklasse: "substantiv", beskrivelse: "Høyfjellslandskapet, ofte brukt poetisk." },
  { ord: "Trolldom", ordklasse: "substantiv", beskrivelse: "Magi eller hekseri fra nordisk folketro." },
  { ord: "Villmark", ordklasse: "substantiv", beskrivelse: "Uberørt natur langt fra bebyggelse." },
  { ord: "Budeie", ordklasse: "substantiv", beskrivelse: "Kvinne som stelte dyra og lagde ost og smør på setra." },
  { ord: "Høylytt", ordklasse: "adjektiv", beskrivelse: "Med høy stemme, bråkete." },
  { ord: "Kjøttkake", ordklasse: "substantiv", beskrivelse: "Norsk husmannskost: formede kaker av kjøttdeig." },
  { ord: "Snøsmelting", ordklasse: "substantiv", beskrivelse: "Perioden om våren når snøen tiner og forsvinner." },
  { ord: "Uvøren", ordklasse: "adjektiv", beskrivelse: "Uforsiktig og tankeløs i oppførsel." },
  { ord: "Spøkefull", ordklasse: "adjektiv", beskrivelse: "Leken og humoristisk, glad i å tulle." },
  { ord: "Klarvær", ordklasse: "substantiv", beskrivelse: "Helt klar himmel uten skyer." },
  { ord: "Nordsken", ordklasse: "substantiv", beskrivelse: "Nordlys – det magiske grønne lyset på nattehimmelen." },
  { ord: "Fossedur", ordklasse: "substantiv", beskrivelse: "Den dype, jevne lyden av en foss." },
  { ord: "Friluftsmenneske", ordklasse: "substantiv", beskrivelse: "En person som elsker å være ute i naturen." },
  { ord: "Stillit", ordklasse: "substantiv", beskrivelse: "Fullstendig stillhet og ro." },
  { ord: "Kjenne", ordklasse: "verb", beskrivelse: "Å føle eller sanse noe – også: å ha kjennskap til." },
  { ord: "Underfundig", ordklasse: "adjektiv", beskrivelse: "Lur, listig og med skjult humor." },
  { ord: "Brødskive", ordklasse: "substantiv", beskrivelse: "En skive brød – grunnsteinen i norsk matkultur." },
  { ord: "Våryr", ordklasse: "adjektiv", beskrivelse: "Oppstemt og glad over at våren er kommet." },
  { ord: "Sommernatt", ordklasse: "substantiv", beskrivelse: "En lys natt om sommeren, uten skikkelig mørke." },
  { ord: "Strynjord", ordklasse: "substantiv", beskrivelse: "Jord der man strevde med å dyrke, skrinn jord." },
  { ord: "Tåkehav", ordklasse: "substantiv", beskrivelse: "Tåke som ligger som et hav over landskapet." },
  { ord: "Sjøsprøyt", ordklasse: "substantiv", beskrivelse: "Vanndråper som spruter opp fra bølger mot land." },
  { ord: "Isfiske", ordklasse: "substantiv", beskrivelse: "Å fiske gjennom et hull i isen – en vintertradisjon." },
  { ord: "Kyststi", ordklasse: "substantiv", beskrivelse: "En sti som går langs kysten med havutsikt." },
  { ord: "Gildskap", ordklasse: "substantiv", beskrivelse: "Et festlig lag eller selskap med mat og drikke." },
  { ord: "Frostrose", ordklasse: "substantiv", beskrivelse: "Vakre ismønstre som dannes på vinduer i kulde." },
  { ord: "Rømmegrøt", ordklasse: "substantiv", beskrivelse: "Tradisjonell norsk grøt laget av rømme og mel." },
  { ord: "Skogholme", ordklasse: "substantiv", beskrivelse: "En liten skogskledd øy i et vann eller en elv." },
  { ord: "Solskinnsdag", ordklasse: "substantiv", beskrivelse: "En strålende dag med sol fra klar himmel." },
  { ord: "Guffen", ordklasse: "adjektiv", beskrivelse: "Ubehagelig kald og fuktig i luften." },
  { ord: "Heimlengt", ordklasse: "substantiv", beskrivelse: "Sterk lengsel etter hjemstedet sitt – hjemlengsel." },
  { ord: "Tungsindig", ordklasse: "adjektiv", beskrivelse: "Trist, melankolsk og tynget av tunge tanker." },
  { ord: "Bringebær", ordklasse: "substantiv", beskrivelse: "Søte, røde bær som vokser vilt i norsk natur." },
  { ord: "Ruslelansen", ordklasse: "substantiv", beskrivelse: "En rolig spasertur uten mål." },
  { ord: "Gullrekke", ordklasse: "substantiv", beskrivelse: "En serie med suksesser etter hverandre." },
  { ord: "Himmelvid", ordklasse: "adjektiv", beskrivelse: "Enorm, uendelig stor – så vid som himmelen." },
  { ord: "Moltefest", ordklasse: "substantiv", beskrivelse: "Feiring når multene er modne og klare for plukking." },
  { ord: "Grautregn", ordklasse: "substantiv", beskrivelse: "Tykt, tungt regn som faller tett og kraftig." },
  { ord: "Saueflokk", ordklasse: "substantiv", beskrivelse: "En gruppe sauer som beiter sammen – typisk norsk syn." },
  { ord: "Bjørkesus", ordklasse: "substantiv", beskrivelse: "Lyden av vind gjennom bjørketrærnes blader." },
  { ord: "Vimsete", ordklasse: "adjektiv", beskrivelse: "Distré, forvirret og lett å distrahere." },
  { ord: "Lurefaks", ordklasse: "substantiv", beskrivelse: "En lur og listig person som lurer andre." },
  { ord: "Godfot", ordklasse: "substantiv", beskrivelse: "God relasjon – å komme på godfot med noen." },
  { ord: "Havblikk", ordklasse: "substantiv", beskrivelse: "Helt stille, speilblankt hav uten bølger." },
  { ord: "Nøtteknepp", ordklasse: "substantiv", beskrivelse: "Knekking av nøtter – også om vanskelige problemer." },
  { ord: "Måneskinn", ordklasse: "substantiv", beskrivelse: "Lyset fra månen som belyser natten." },
  { ord: "Utsøkt", ordklasse: "adjektiv", beskrivelse: "Av svært høy kvalitet, nydelig og raffinert." },
  { ord: "Blomstereng", ordklasse: "substantiv", beskrivelse: "En eng full av ville blomster i mange farger." },
  { ord: "Regnskur", ordklasse: "substantiv", beskrivelse: "Et kortvarig, men kraftig regnfall." },
  { ord: "Tordenvær", ordklasse: "substantiv", beskrivelse: "Uvær med torden og lyn." },
  { ord: "Søtlaten", ordklasse: "adjektiv", beskrivelse: "Med lyst på noe søtt å spise." },
  { ord: "Skibakke", ordklasse: "substantiv", beskrivelse: "En bakke tilrettelagt for skikjøring." },
  { ord: "Pultost", ordklasse: "substantiv", beskrivelse: "Brun, syrlig norsk ost – en tradisjonsrik spesialitet." },
  { ord: "Kvass", ordklasse: "adjektiv", beskrivelse: "Skarp, bitende – om kniv, kulde eller replikk." },
  { ord: "Fortumlet", ordklasse: "adjektiv", beskrivelse: "Forvirret og svimmel, som om hodet snurrer." },
  { ord: "Stokkdøv", ordklasse: "adjektiv", beskrivelse: "Helt døv, kan ikke høre noe som helst." },
  { ord: "Pinnekjøtt", ordklasse: "substantiv", beskrivelse: "Saltet og tørket lammeribbe – tradisjonell julemat i Vest-Norge." },
  { ord: "Kjøttboller", ordklasse: "substantiv", beskrivelse: "Runde boller av kjøttdeig – klassisk norsk hverdagsmat." },
  { ord: "Våkenatt", ordklasse: "substantiv", beskrivelse: "En natt man tilbringer våken, uten søvn." },
  { ord: "Smelting", ordklasse: "substantiv", beskrivelse: "Prosessen der is eller snø blir til vann." },
  { ord: "Sjøluft", ordklasse: "substantiv", beskrivelse: "Den friske, salte luften nær havet." },
  { ord: "Knivskarp", ordklasse: "adjektiv", beskrivelse: "Ekstremt skarp, som eggen på en kniv." },
  { ord: "Elendig", ordklasse: "adjektiv", beskrivelse: "Svært dårlig, ynkelig eller stakkarslig." },
  { ord: "Fånyttes", ordklasse: "adverb", beskrivelse: "Uten resultat, til ingen nytte." },
  { ord: "Grøssende", ordklasse: "adjektiv", beskrivelse: "Som vekker grøss – skremmende eller uhyggelig." },
  { ord: "Snarrådig", ordklasse: "adjektiv", beskrivelse: "Rask til å tenke og handle, oppfinnsom i pressede situasjoner." },
  { ord: "Tyttebær", ordklasse: "substantiv", beskrivelse: "Små, røde, litt bitre bær – brukes mye til syltetøy i Norge." },
  { ord: "Bekmørke", ordklasse: "substantiv", beskrivelse: "Så mørkt at man ikke kan se hånden foran seg." },
  { ord: "Lynne", ordklasse: "substantiv", beskrivelse: "Gemytt eller temperament – «god lynne» betyr godt humør." },
  { ord: "Langhalm", ordklasse: "substantiv", beskrivelse: "Lange, tynne strå – brukes også om noe som er svært tynt." },
  { ord: "Vågal", ordklasse: "adjektiv", beskrivelse: "Dristig og modig – kanskje litt for modig." },
  { ord: "Himmelsendt", ordklasse: "adjektiv", beskrivelse: "Som sendt fra himmelen, perfekt og velkomment." },
  { ord: "Sjarmtroll", ordklasse: "substantiv", beskrivelse: "En person med uimotståelig sjarm." },
  { ord: "Kløktig", ordklasse: "adjektiv", beskrivelse: "Smart, oppfinnsom og dyktig i tenkning." },
  { ord: "Dobbeltgjenger", ordklasse: "substantiv", beskrivelse: "En person som likner svært mye på en annen." },
  { ord: "Spikergalen", ordklasse: "adjektiv", beskrivelse: "Helt gal, fullstendig sprø." },
  { ord: "Godbit", ordklasse: "substantiv", beskrivelse: "En deilig liten smakebit eller snacks." },
  { ord: "Krydderhylle", ordklasse: "substantiv", beskrivelse: "Hylle med krydder på kjøkkenet – noe alle norske hjem har." },
  { ord: "Sovepute", ordklasse: "substantiv", beskrivelse: "Pute man hviler hodet på – også metafor for lat holdning." },
  { ord: "Skarlagen", ordklasse: "substantiv", beskrivelse: "En dyp, intens rød farge." },
  { ord: "Kråkefot", ordklasse: "substantiv", beskrivelse: "Stygg eller uleselig håndskrift." },
  { ord: "Silkeglatt", ordklasse: "adjektiv", beskrivelse: "Helt glatt og myk som silke." },
  { ord: "Bleknebb", ordklasse: "substantiv", beskrivelse: "En uerfaren person, en grønskolling." },
  { ord: "Tusenfryd", ordklasse: "substantiv", beskrivelse: "En liten, hvit og gul vårblomst – også: en person som alltid er glad." },
  { ord: "Omsorg", ordklasse: "substantiv", beskrivelse: "Å ta vare på noen med varme og oppmerksomhet." },
  { ord: "Rampete", ordklasse: "adjektiv", beskrivelse: "Uskikkelig og tullete, spesielt om barn." },
  { ord: "Frydefull", ordklasse: "adjektiv", beskrivelse: "Full av glede og fryd." },
  { ord: "Hakkespett", ordklasse: "substantiv", beskrivelse: "Fugl som hakker i trær – også: en energisk person." },
  { ord: "Skulderklapp", ordklasse: "substantiv", beskrivelse: "Et klapp på skulderen som tegn på anerkjennelse." },
  { ord: "Fjærlett", ordklasse: "adjektiv", beskrivelse: "Så lett som en fjær – nesten vektløs." },
  { ord: "Smaragdgrønn", ordklasse: "adjektiv", beskrivelse: "Dyp, klar grønn farge som edelstenen smaragd." },
  { ord: "Ramsalt", ordklasse: "adjektiv", beskrivelse: "Svært salt – brukes også om skarp humor eller kritikk." },
  { ord: "Bakverk", ordklasse: "substantiv", beskrivelse: "Samlebetegnelse for alt som bakes: kaker, brød, boller." },
  { ord: "Eventyrlyst", ordklasse: "substantiv", beskrivelse: "Lysten til å reise og oppleve noe spennende." },
  { ord: "Ubetenkt", ordklasse: "adjektiv", beskrivelse: "Gjort uten å tenke seg om først." },
  { ord: "Fjellstø", ordklasse: "adjektiv", beskrivelse: "Stødig og trygg, som om man har fast grunn under føttene." },
  { ord: "Glattbarbert", ordklasse: "adjektiv", beskrivelse: "Helt uten skjegg, glattraket i ansiktet." },
  { ord: "Kjempefin", ordklasse: "adjektiv", beskrivelse: "Veldig fin, flott. En norsk hverdagsforsterkning." },
  { ord: "Snøhule", ordklasse: "substantiv", beskrivelse: "Et rom gravd ut i snøen for ly eller lek." },
  { ord: "Pinnedyr", ordklasse: "substantiv", beskrivelse: "Insekt som ser ut som en pinne – mester i kamuflasje." },
  { ord: "Kuvending", ordklasse: "substantiv", beskrivelse: "En plutselig og fullstendig endring av standpunkt." },
  { ord: "Søvngjengar", ordklasse: "substantiv", beskrivelse: "En person som går i søvne." },
  { ord: "Gravalvorlig", ordklasse: "adjektiv", beskrivelse: "Dypt alvorlig, uten et snev av humor." },
  { ord: "Strandhogg", ordklasse: "substantiv", beskrivelse: "Et vikingtokt der man plyndret langs kysten." },
  { ord: "Morild", ordklasse: "substantiv", beskrivelse: "Bioluminescens i sjøen – havet som lyser opp om natten." },
  { ord: "Seterbu", ordklasse: "substantiv", beskrivelse: "En enkel hytte på setra der budeien bodde om sommeren." },
  { ord: "Gjennomtrekk", ordklasse: "substantiv", beskrivelse: "Kald luftstrøm som trekker gjennom et rom." },
  { ord: "Lynild", ordklasse: "substantiv", beskrivelse: "Et lyn – en plutselig, kraftig elektrisk gnist fra himmelen." },
  { ord: "Vassrett", ordklasse: "adjektiv", beskrivelse: "Helt horisontalt – vannrett som en stille vannflate." },
  { ord: "Dådyr", ordklasse: "substantiv", beskrivelse: "En slank og vakker hjorteart med flekket pels." },
  { ord: "Gyldent", ordklasse: "adjektiv", beskrivelse: "Med en varm, gyllen farge som gull." },
  { ord: "Aftenstjerne", ordklasse: "substantiv", beskrivelse: "Den første synlige stjernen etter solnedgang – ofte Venus." },
  { ord: "Draumekveld", ordklasse: "substantiv", beskrivelse: "En perfekt, drømmende kveld – gjerne ute i naturen." },
  { ord: "Julestemning", ordklasse: "substantiv", beskrivelse: "Den varme, nostalgiske følelsen som oppstår i juletiden." },
  { ord: "Blåkveite", ordklasse: "substantiv", beskrivelse: "En nordnorsk flatfisk som lever på dypt vann." },
  { ord: "Iskrystall", ordklasse: "substantiv", beskrivelse: "En vakker, geometrisk krystall dannet av frossent vann." },
  { ord: "Nordavind", ordklasse: "substantiv", beskrivelse: "Kald vind fra nord – ofte bitende om vinteren." },
  { ord: "Drøymande", ordklasse: "adjektiv", beskrivelse: "Med drømmende blikk, fjern og tankefull." },
  { ord: "Strileregn", ordklasse: "substantiv", beskrivelse: "Vedvarende, surt regn – typisk for Vestlandet." },
  { ord: "Fuglekvitter", ordklasse: "substantiv", beskrivelse: "Den glade lyden av fugler som synger." },
  { ord: "Utskyting", ordklasse: "substantiv", beskrivelse: "Å skyte noe ut – nyttårsraketter eller romraketter." },
  { ord: "Sjømann", ordklasse: "substantiv", beskrivelse: "En person som jobber til sjøs – stor norsk tradisjon." },
  { ord: "Bygdesladder", ordklasse: "substantiv", beskrivelse: "Rykter og prat som sprer seg i et lite samfunn." },
  { ord: "Skog", ordklasse: "substantiv", beskrivelse: "Stort område med trær – Norge er dekket av det." },
  { ord: "Norgesglass", ordklasse: "substantiv", beskrivelse: "Et ikonisk norsk hermetikkglass med klips – brukt i generasjoner." },
  { ord: "Brunost", ordklasse: "substantiv", beskrivelse: "Brun, søt norsk ost – ikonisk og unik for Norge." },
  { ord: "Knekkebrød", ordklasse: "substantiv", beskrivelse: "Tynt, sprøtt brød – en stapelvare på norske kjøkken." },
  { ord: "Gåsegang", ordklasse: "substantiv", beskrivelse: "Å gå i rekke etter hverandre, som gjess." },
  { ord: "Raudrev", ordklasse: "substantiv", beskrivelse: "Den vanligste revarten i Norge med rød pels." },
  { ord: "Solnedgang", ordklasse: "substantiv", beskrivelse: "Det øyeblikket solen synker under horisonten." },
  { ord: "Lundefugl", ordklasse: "substantiv", beskrivelse: "En fargerik sjøfugl med stor nebb – Norges mest folkekjære fugl." },
  { ord: "Vidsynt", ordklasse: "adjektiv", beskrivelse: "Tolerant og åpen for nye ideer og synspunkter." },
  { ord: "Påhitt", ordklasse: "substantiv", beskrivelse: "En kreativ idé eller et innfall, gjerne litt rar." },
  { ord: "Gjæv", ordklasse: "adjektiv", beskrivelse: "Raus, sjenerøs og gavmild, gjerne dialektalt." },
  { ord: "Helsprø", ordklasse: "adjektiv", beskrivelse: "Helt sprø, gal – om person eller situasjon." },
  { ord: "Reinsdyr", ordklasse: "substantiv", beskrivelse: "Majestetisk hjortedyr som lever i Norges fjellområder." },
  { ord: "Knøttliten", ordklasse: "adjektiv", beskrivelse: "Usedvanlig liten, bittesmå." },
  { ord: "Bamseklem", ordklasse: "substantiv", beskrivelse: "En stor, varm og tett klem." },
  { ord: "Ordholden", ordklasse: "adjektiv", beskrivelse: "Å holde det man har lovet." },
  { ord: "Silregn", ordklasse: "substantiv", beskrivelse: "Vedvarende, stille regn som siler ned." },
  { ord: "Grønnkål", ordklasse: "substantiv", beskrivelse: "Krøllete grønn kål – en supermat som tåler norsk kulde." },
  { ord: "Rorbua", ordklasse: "substantiv", beskrivelse: "En fiskerbu ved sjøen i Lofoten – nå ofte turistbolig." },
  { ord: "Snøskred", ordklasse: "substantiv", beskrivelse: "Store mengder snø som raser ned en fjellside." },
  { ord: "Langrennsski", ordklasse: "substantiv", beskrivelse: "Smale ski for langrenn – Norges nasjonalsport." },
  { ord: "Stabbeis", ordklasse: "substantiv", beskrivelse: "Overfroren is som gjør det glatt og farlig." },
  { ord: "Valnøtt", ordklasse: "substantiv", beskrivelse: "En nøtt med hardt skall og hjernelignende kjerne." },
  { ord: "Sjelfred", ordklasse: "substantiv", beskrivelse: "Indre ro og fred i sinnet." },
  { ord: "Kjempeglad", ordklasse: "adjektiv", beskrivelse: "Utrolig glad, overlykkelig." },
  { ord: "Torskefiske", ordklasse: "substantiv", beskrivelse: "Tradisjonelt fiske etter torsk – ryggraden i norsk kystkultur." },
  { ord: "Blåbærtue", ordklasse: "substantiv", beskrivelse: "En tue i skogen full av blåbær, klar til plukking." },
  { ord: "Pannekake", ordklasse: "substantiv", beskrivelse: "Norske pannekaker – tynnere enn amerikanske, med sukker og sitron." },
  { ord: "Samefolket", ordklasse: "substantiv", beskrivelse: "Norges urfolk med rik kultur og tradisjon i nord." },
  { ord: "Solgløtt", ordklasse: "substantiv", beskrivelse: "Et kort glimt av sol mellom skyene." },
  { ord: "Avslappet", ordklasse: "adjektiv", beskrivelse: "Rolig, avslappet og uten stress." },
  { ord: "Ørkenblomst", ordklasse: "substantiv", beskrivelse: "En blomst som overlever i tørt klima – metafor for styrke." },
  { ord: "Fjording", ordklasse: "substantiv", beskrivelse: "En kraftig norsk hesterase fra Vestlandet." },
  { ord: "Grillsesong", ordklasse: "substantiv", beskrivelse: "Den norske grillsesongen – når nordmenn endelig kan grille ute." },
  { ord: "Tussemørke", ordklasse: "substantiv", beskrivelse: "Skumringstime da tusser og troll var ute i folkemytologien." },
  { ord: "Solbrent", ordklasse: "adjektiv", beskrivelse: "Med huden rødsvedd av for mye sol." },
  { ord: "Nøtteskall", ordklasse: "substantiv", beskrivelse: "Det harde skallet rundt en nøtt – «i et nøtteskall» betyr kort oppsummert." },
  { ord: "Elvebredd", ordklasse: "substantiv", beskrivelse: "Bredden langs en elv – et fint sted å sitte." },
  { ord: "Sjøvett", ordklasse: "substantiv", beskrivelse: "Kunnskap og regler for sikkerhet på sjøen." },
  { ord: "Hardbarket", ordklasse: "adjektiv", beskrivelse: "Herdet av erfaring, tøff og utholdende." },
  { ord: "Steinalder", ordklasse: "substantiv", beskrivelse: "Den eldste menneskelige tidsperioden – da stein var verktøy." },
  { ord: "Gjespende", ordklasse: "adjektiv", beskrivelse: "Som gjesper, søvnig eller kjedsom." },
  { ord: "Fjellbekk", ordklasse: "substantiv", beskrivelse: "En liten bekk av klart, kaldt vann som renner ned fra fjellet." },
  { ord: "Lysløype", ordklasse: "substantiv", beskrivelse: "Opplyst skiløype for langrenn om kvelden." },
  { ord: "Hyggekrok", ordklasse: "substantiv", beskrivelse: "Et lite, koselig hjørne i hjemmet der man kan slappe av." },
  { ord: "Vaffelhjerte", ordklasse: "substantiv", beskrivelse: "Hjerteformet norsk vaffel – alltid servert med rømme og syltetøy." },
  { ord: "Iskald", ordklasse: "adjektiv", beskrivelse: "Ekstremt kald, som is." },
  { ord: "Sjøfart", ordklasse: "substantiv", beskrivelse: "Norsk skipstrafikk og maritim virksomhet gjennom tidene." },
  { ord: "Grautfjøl", ordklasse: "substantiv", beskrivelse: "Brettet man røra grøten på – konkret og jordnært." },
  { ord: "Seterrosa", ordklasse: "substantiv", beskrivelse: "Rosemaling på seterbuene – typisk norsk folkekunst." },
  { ord: "Solstreif", ordklasse: "substantiv", beskrivelse: "En smal stripe sollys som faller gjennom et vindu eller skylag." },
  { ord: "Kveldsmat", ordklasse: "substantiv", beskrivelse: "Kveldsmat – det siste måltidet, vanligvis brødskiver." },
  { ord: "Slappfisk", ordklasse: "substantiv", beskrivelse: "En person uten energi eller initiativ – lat og viljesvak." },
  { ord: "Humørspreder", ordklasse: "substantiv", beskrivelse: "En person som sprer godt humør rundt seg." },
  { ord: "Havgap", ordklasse: "substantiv", beskrivelse: "Ytterste punktet mot havet – der land møter åpent hav." },
  { ord: "Multebær", ordklasse: "substantiv", beskrivelse: "Gylne bær fra myr i Nord-Norge – en sjelden delikatesse." },
  { ord: "Dugfrisk", ordklasse: "adjektiv", beskrivelse: "Frisk som morgenduggen – ny og uberørt." },
  { ord: "Fjøsnisse", ordklasse: "substantiv", beskrivelse: "Liten, overnaturlig vesen fra folketroen som bodde i fjøset." },
  { ord: "Bølgedal", ordklasse: "substantiv", beskrivelse: "Bunnen mellom to bølger – metafor for lavpunktet." },
  { ord: "Kveldssol", ordklasse: "substantiv", beskrivelse: "Den varme, gylne solen sent på ettermiddagen." },
  { ord: "Snøkledde", ordklasse: "adjektiv", beskrivelse: "Dekket av et hvitt lag med snø." },
  { ord: "Regntung", ordklasse: "adjektiv", beskrivelse: "Mørke skyer fulle av regn – også: trist stemning." },
  { ord: "Husmannskost", ordklasse: "substantiv", beskrivelse: "Enkel, tradisjonell norsk mat – kjøttkaker, lapskaus, fårikål." },
  { ord: "Fjellspreng", ordklasse: "substantiv", beskrivelse: "Frostvær som sprekker fjell – naturens kraft." },
  { ord: "Tankeflom", ordklasse: "substantiv", beskrivelse: "En overveldende strøm av tanker." },
  { ord: "Mosegrodd", ordklasse: "adjektiv", beskrivelse: "Overgrodd med mose – om steiner, trær eller gamle bygninger." },
  { ord: "Bærepose", ordklasse: "substantiv", beskrivelse: "Plastpose til å bære varer i – en norsk kiosk-klassiker." },
  { ord: "Overstadig", ordklasse: "adjektiv", beskrivelse: "Overdrevent beruset – «overstadig beruset»." },
  { ord: "Huldra", ordklasse: "substantiv", beskrivelse: "Vakker, forlokkende skapning fra norsk folketro med hale." },
  { ord: "Utemøbler", ordklasse: "substantiv", beskrivelse: "Møbler for bruk ute – nordmenns stolthet om sommeren." },
  { ord: "Tjuvstart", ordklasse: "substantiv", beskrivelse: "Å starte noe før alle andre – komme i gang tidlig." },
  { ord: "Kaffeslabberas", ordklasse: "substantiv", beskrivelse: "Sosialt samvær over kaffe og kaker." },
  { ord: "Gjetost", ordklasse: "substantiv", beskrivelse: "En søt, brun ost tradisjonelt laget av geitmlk." },
  { ord: "Kjøkkenbenk", ordklasse: "substantiv", beskrivelse: "Arbeidsflaten på kjøkkenet der maten tilberedes." },
  { ord: "Krumkake", ordklasse: "substantiv", beskrivelse: "Tynt, krøllet julekake stekt i eget jern." },
  { ord: "Solkrem", ordklasse: "substantiv", beskrivelse: "Krem som beskytter huden mot solens UV-stråler." },
  { ord: "Fjellrev", ordklasse: "substantiv", beskrivelse: "En sjelden og truet rev som lever i høyfjellet." },
  { ord: "Oppvarming", ordklasse: "substantiv", beskrivelse: "Å varme opp kroppen før trening – eller å varme mat." },
  { ord: "Drømmeland", ordklasse: "substantiv", beskrivelse: "Det mentale stedet man er i når man dagdrømmer." },
  { ord: "Solstikk", ordklasse: "substantiv", beskrivelse: "Ubehag etter for mye sol – hodepine og kvalme."  },
  { ord: "Lynkurs", ordklasse: "substantiv", beskrivelse: "Et intensivt, kort kurs for rask læring." },
  { ord: "Norgesferie", ordklasse: "substantiv", beskrivelse: "Ferie tilbragt i Norge – en tradisjonsrik vane." },
  { ord: "Fjellvann", ordklasse: "substantiv", beskrivelse: "Et stille, kaldt vann høyt oppe i fjellet." },
  { ord: "Tåkefyrste", ordklasse: "substantiv", beskrivelse: "En person som er distré og virker å leve i sin egen verden." },
  { ord: "Storslått", ordklasse: "adjektiv", beskrivelse: "Imponerende stort og vakkert – majestetisk." },
  { ord: "Søvnløs", ordklasse: "adjektiv", beskrivelse: "Ute av stand til å sove." },
  { ord: "Gapskratt", ordklasse: "substantiv", beskrivelse: "Høylytt, uhemmet latter med åpen munn." },
  { ord: "Pepperkake", ordklasse: "substantiv", beskrivelse: "Julekake krydret med ingefær og kanel – formet og dekorert." },
  { ord: "Lutefisk", ordklasse: "substantiv", beskrivelse: "Tørket hvitfisk bløtlagt i lut – tradisjonell norsk julemat." },
  { ord: "Takras", ordklasse: "substantiv", beskrivelse: "Snø eller is som raser ned fra et tak." },
  { ord: "Hjertegod", ordklasse: "adjektiv", beskrivelse: "Vennlig og god helt inn i hjertet." },
  { ord: "Sjøørret", ordklasse: "substantiv", beskrivelse: "En ørret som vandrer mellom elv og sjø – populær sportsfisk." },
  { ord: "Kribblete", ordklasse: "adjektiv", beskrivelse: "Å kjenne en prikking i kroppen av spenning eller utålmodighet." },
  { ord: "Elgvandring", ordklasse: "substantiv", beskrivelse: "Elgens sesongmessige forflytning mellom beiteområder." },
  { ord: "Havsule", ordklasse: "substantiv", beskrivelse: "En stor, hvit sjøfugl som stupdykker etter fisk." },
];

/**
 * Get the word of the day based on the current date.
 * Uses day-of-year to cycle through the word list (366 words).
 */
export function getDagensOrd(date?: Date): DagensOrd {
  const d = date || new Date();
  const start = new Date(d.getFullYear(), 0, 0);
  const diff = d.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return ordliste[dayOfYear % ordliste.length];
}
